### ISSUE TITLE
Add psubst to Chocolatey Packages

### ISSUE THREAD

**Issue by ihorzenich** [ildar-shaimordanov/psubst#14]
Please add *psubst* to [Chocolatey](https://chocolatey.org/packages) (package manager for Windows), so that we will be able to install it via something like `choco install psubst` in `cmd`.

How-to guide here: https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart

**Comment by ildar-shaimordanov** [comment]
I don't use Chocolatey in my work now. It would be interesting experience to study new tool. Most probably I will do it later. Using tools like Chocolatey seems too complicated to install such a kind of very simple scripts. Right now you can download and unpack it somewhere in PATH. 

Keep this issue opened for the future.

**Comment by ildar-shaimordanov** [comment]
@ihorzenich 

It's been 2.5 years since you asked to to create a Chocolatey package for this script. I spent few hours studying the manager and the ways how to create the packages for it. I think I knew enough to embed psubst into the chocolatey package. The package has been created and filed, you can find it by this link https://chocolatey.org/packages/psubst/2.6.2. Actually, it's in the moderator queue.

**Comment by ildar-shaimordanov** [comment]
The request is completed. I close this issue assuming it's resolved.
