### ISSUE TITLE
Windows Updates and Microsoft Store hate A: and B: drives in Windows 10

### ISSUE THREAD

**Issue by bourbongoat** [ildar-shaimordanov/psubst#16]
After months of struggling with this, I finally realized the uniting factor between 2 machines that were persistently having errors downloading from the Microsoft Store and Windows Update, the fact that I had a b:\ drive mapped to a folder on another drive.  You'll get a common 0x80070057 error with solutions all over the web, but none of them will fix it.  Deleting the registry key for the b:\ drive will fix it, however.  I've also reproduced the issue with the a:\ drive, but others seem to work without issue.  I'm passing the issue on to Microsoft, but just thought you might want to consider a disclaimer.

**Comment by ildar-shaimordanov** [comment]
@bourbongoat 
thank you for your feedback. Actually I am not actively focusing on this project, however I try to support it as much as possible. A bit later I will find time to update the "Issues and troubleshooting" page with the reference to your message.

**Comment by ildar-shaimordanov** [comment]
@bourbongoat 
Thank again for your feedback. This issue was described on the page https://github.com/ildar-shaimordanov/psubst/blob/master/IssuesAndTroubleshooting.md#mapping-a-or-b-to-a-folder-on-another-drive.

**Comment by aplatypus** [comment]
@bourbongoat

I have found using `psubst /d a:`  works better than directly editing the registry.

**Comment by jmchandonia** [comment]
@ildar-shaimordanov , please make this warning MUCH more prominent, since psubst'ing A: or B: completely breaks updates in Windows 10 and 11, including security updates.  As @bourbongoat commented, it can take months to trace these problems back to psubst, since Microsoft's error messages are misleading. @aplatypus's method for undoing it works well, but this issue is hard to find since it is closed and is not referred to in the main README.  I'd recommend not even allowing A: or B: unless the user gets a warning and runs with some sort of "force" flag!

**Comment by ildar-shaimordanov** [comment]
@jmchandonia 

Thank you for pointing to the scale of the issue. I am afraid that introducing a new flag won't fix it but gives more troubles in distinguishing the functionalities of two different "force" flags.

To this moment I am going to add more explanation to the "Issues and Troubleshooting" page and make the link thereto more remarkable.
